MainApp/urls.py
from django.conf.urls import patterns, include, url
from MainApp import views
urlpatterns = patterns('',
    url(r'^$', views.home),
    url(r'^groups/$', views.groups),
    url(r'^groups/(?P<group_id>[0-9]*)/$', views.groups_view),
    url(r'^groups_new/', views.groups_new),
    url(r'^tasks/$', views.tasks),
    url(r'^tasks/(?P<task_id>[0-9]*)/$', views.tasks_view),
    url(r'^tasks_new/', views.tasks_new),
    url(r'^profile/$', views.profile),
    url(r'^profile/(?P<user_id>[0-9]*)/$', views.user_view),
    url(r'^comment/(?P<comment_id>[0-9]*)/$', views.comment_view),
    url(r'^small_task_list/$', views.small_task_list),
    url(r'^calendarjson/$', views.calendarjson),
    url(r'^delete_task/$', views.delete_task),
    url(r'^delete_comment/$', views.delete_comment),
    url(r'^delete_group/$', views.delete_group),
    url(r'^calendarmore/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.calendarmore)
)

TaskManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from MainApp.views import home

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TaskManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', home),
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('login.urls')),
    url(r'', include('MainApp.urls')),
)

login/urls.py
from django.conf.urls import patterns, include, url,static

from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/$', views.login),
    url(r'^new_user/$',views.new_user),
    url(r'^logout/$', views.logout),
    url(r'^register/$', views.register),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

)

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


# Create your models here.
class Group(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=300)
	users = models.ManyToManyField(User)
	created = models.DateTimeField(auto_now_add=True)

	def get_absolute_url(self):
		return reverse('MainApp.views.groups_view', args=[str(self.id)])

	def type(self):
		return self._meta.verbose_name

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		ordering = ["-created"]

class Task(models.Model):
	name = models.CharField(max_length=50)
	users = models.ManyToManyField(User)
	description = models.CharField(max_length=300)
	deadline = models.DateField()
	group = models.ForeignKey(Group, blank=True, null= True)
	priority = models.PositiveSmallIntegerField(blank=True, null= True)
	workload = models.FloatField(blank=True, null= True)
	created = models.DateTimeField(auto_now_add=True)

	def get_absolute_url(self):
		return reverse('MainApp.views.tasks_view', args=[str(self.id)])

	def type(self):
		return self._meta.verbose_name

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		ordering = ["-created"]


class Comment(models.Model):
	user = models.ForeignKey(User)
	comment = models.CharField(max_length=150)
	created = models.DateTimeField(auto_now_add=True)
	edited = models.DateTimeField(auto_now=True)
	task = models.ForeignKey(Task, blank=True, null= True)
	group = models.ForeignKey(Group, blank=True, null= True)

	def get_absolute_url(self):
		return reverse('MainApp.views.comment_view', args=[str(self.id)])

	def type(self):
		return self._meta.verbose_name

	def __unicode__(self):
		return "Comment by "+unicode(self.user)+" on "+unicode(self.created)

	class Meta:
		ordering = ["-created"]

login/models.py
from django.db import models

# Create your models here.

MainApp/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest 
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from MainApp.models import *
from main_forms import *
import sys
import json
import time

@login_required
def home(request):
	#print >>sys.stderr, 'TEST PRINT PLS IGNORE'
	user = request.user

	task_list = Task.objects.filter(users = request.user)

	groups = Group.objects.filter(users = request.user).order_by('-created')[:10]
	tasks = task_list.order_by('-created')[:10]
	comments = Comment.objects.filter(Q(group__in=groups) | Q(task__in=tasks)).order_by('-created')[:10]

	latest = list(groups) + list(tasks) +list(comments)
	latest_sorted = sorted(latest, key=lambda x: x.created, reverse=True)[:10]

	return render_to_response('MainApp/home.html', {'user':request.user, 'latest':latest_sorted, 'task_list':task_list})

def ajax_view(function):
	#decorator function
	def _view(request, *args, **kwargs):
		if request.is_ajax() or request.method == 'POST':
			return function(request, *args, **kwargs)
		else: 
			#this could be better
			return HttpResponseRedirect("/")

	return _view	

@ajax_view
def groups(request):
	group_list = Group.objects.filter(users = request.user)
	return render_to_response('MainApp/groups.html', {'user':request.user, 'group_list':group_list})

@ajax_view
def groups_new(request):
	if request.method == 'POST': # If the form has been submitted...
		form = GroupForm(request.POST) # A form bound to the POST data
		if form.errors:
			errorjson = send_errors(form.errors)
			return HttpResponseBadRequest(errorjson)
		if form.is_valid(): # All validation rules pass
			form.save()
	else:
		form = GroupForm() # An unbound form

	#return render_to_response('MainApp/groups_new.html', context_instance=RequestContext(request, {'form': form}))
	return render_to_response('MainApp/groups_new.html',{'user':request.user, 'form':form}, context_instance=RequestContext(request)) 

	
@ajax_view
def groups_view(request, group_id):
	#need to check if user is in group here
	try:
		group = Group.objects.get(id = group_id)
	except Group.DoesNotExist:
		#some sort of error page here?
		return HttpResponseRedirect("/")

	if request.method == 'POST': # If the form has been submitted...
		form = CommentForm(request.POST) # A form bound to the POST data
		if form.errors:
			errorjson = send_errors(form.errors)
			return HttpResponseBadRequest(errorjson)
		if form.is_valid(): # All validation rules pass
			new_comment = form.save(commit = False)
			new_comment.user = request.user
			new_comment.task = None
			new_comment.group = group
			new_comment.save()
			return HttpResponseRedirect("/") # Redirect after POST
	else:
		form = CommentForm() # An unbound form

	task_list = Task.objects.filter(group = group)
	comment_list = Comment.objects.filter(group = group)
	return render_to_response('MainApp/group.html', {'group':group, 'task_list':task_list, 'comment_list':comment_list, 'form':form}, context_instance=RequestContext(request))

@ajax_view
def tasks(request):
	task_list = Task.objects.filter(users = request.user)
	return render_to_response('MainApp/tasks.html', {'user':request.user, 'task_list':task_list})

@ajax_view
def tasks_new(request):
	if request.method == 'POST': # If the form has been submitted...
		form = TaskForm(request.POST) # A form bound to the POST data
		if form.errors:
			errorjson = send_errors(form.errors)
			return HttpResponseBadRequest(errorjson)
		if form.is_valid(): # All validation rules pass
			form.save()
	else:
		form = TaskForm() # An unbound form

	#return render_to_response('MainApp/groups_new.html', context_instance=RequestContext(request, {'form': form}))
	return render_to_response('MainApp/tasks_new.html',{'user':request.user, 'form':form}, context_instance=RequestContext(request)) 

@ajax_view
def delete_task(request):
	task_id = request.POST["id"]
	try:
		task = Task.objects.get(id = task_id)
	except Task.DoesNotExist:
		return HttpResponse("Task does not exist.")

	if task.users.filter(id = request.user.id).exists():
		task.delete()
		return HttpResponse("Successfully deleted task.")
		
	else:
		return HttpResponse("You don't have the right to delete this.")

@ajax_view
def delete_group(request):
	group_id = request.POST["id"]
	try:
		group = Group.objects.get(id = group_id)
	except Task.DoesNotExist:
		return HttpResponse("Group does not exist.")

	if group.users.filter(id = request.user.id).exists():
		group.delete()
		return HttpResponse("Successfully deleted group.")
		
	else:
		return HttpResponse("You don't have the right to delete this.")


@ajax_view
def delete_comment(request):
	comment_id = request.POST["id"]
	try:
		comment = Comment.objects.get(id=comment_id)
	except Comment.DoesNotExist:
		return HttpResponse("Comment does not exist.")
	if (comment.user==request.user):
		if comment.task:
			response = HttpResponse("/tasks/"+ str(comment.task.id) +"/")
		else:
			response = HttpResponse("/groups/"+ str(comment.group.id) +"/")
		comment.delete()
		return response
	else:
		return HttpResponse("You don't have the right to delete this.")

@ajax_view
def tasks_view(request, task_id):
	#need to check if user is in task here
	try:
		task = Task.objects.get(id = task_id)
	except Task.DoesNotExist:
		#some sort of error page here?
		return HttpResponseRedirect("/")

	if request.method == 'POST': # If the form has been submitted...
		form = CommentForm(request.POST) # A form bound to the POST data
		if form.errors:
			errorjson = send_errors(form.errors)
			return HttpResponseBadRequest(errorjson)
		if form.is_valid(): # All validation rules pass
			new_comment = form.save(commit = False)
			new_comment.user = request.user
			new_comment.task = task
			new_comment.group = None
			new_comment.save()
	else:
		form = CommentForm() # An unbound form
	
	comment_list = Comment.objects.filter(task = task)
	return render_to_response('MainApp/task.html', {'task':task, 'comment_list':comment_list, 'form':form}, context_instance=RequestContext(request))


@ajax_view
def comment_view(request, comment_id):
	try:
		comment = Comment.objects.get(id = comment_id)
	except Comment.DoesNotExist:
		#some sort of error page here?
		return HttpResponseRedirect("/")
	#need to check if user is in group here
	return render_to_response('MainApp/comment.html', {'comment':comment})

@ajax_view	
def profile(request):
	group_list = Group.objects.filter(users = request.user)
	return render_to_response('MainApp/profile.html', {'user':request.user})

@ajax_view
def user_view(request, user_id):
	try:
		user = User.objects.get(id = user_id)
	except User.DoesNotExist:
		#some sort of error page here?
		return HttpResponseRedirect("/")
	#need to check if user is in group here

	group_list = Group.objects.filter(users = user)
	return render_to_response('MainApp/user.html', {'user':user, 'group_list': group_list})

@ajax_view
def small_task_list(request):
	task_list = Task.objects.filter(users = request.user).order_by('deadline')[:5]
	return render_to_response('MainApp/small_task_list.html', {'task_list':task_list})


def send_errors(errors):
	errors_dict = {}
	for error in errors:
		e = errors[error]
		errors_dict[error] = unicode(e)
	return json.dumps(errors_dict)

@ajax_view
def calendarjson(request):

	callback = request.GET.get('callback', '')

	try:
		task = Task.objects.filter(users=request.user).order_by('name').order_by('deadline')
	except Task.DoesNotExist:
		return HttpResponseRedirect("/")

	#Count events per day
	evtPerDay = 0
	arrayEvents = []
	moreOptEvents = []
	prevEvent = {}
	count = 0
	# Loop through all the events from database
	for i in task:
		#Variable used to convert object to dic
		tmpDict = {}
		if len(i.name) > 6:
			tmpDict['title'] = i.name[:6] + "..."
		else:
			tmpDict['title'] = i.name
		tmpDict['start'] = time.mktime(i.deadline.timetuple())
		tmpDict['url'] = "/tasks/" + str(i.pk) + "/"
		if i.priority == 1:
			tmpDict['bgColor'] = 'red'
		elif i.priority == 2:
			tmpDict['bgColor'] = 'yellow'
		elif i.priority == 3:
			tmpDict['bgColor'] = 'green'

		# Check if prevEvent exists and if prevEvent is on same day as the current event
		if prevEvent and (prevEvent['start'] == tmpDict['start']) :
			count = count + 1
			if count >= 1:
				tmpDict['title'] = 'More...'
				tmpDict['url'] = ''
				tmpDict['bgColor'] = 'gray'
		else:
			count = 0

		if (count <= 1):
			arrayEvents.append(tmpDict)
		prevEvent = tmpDict

	allEvents = {}
	allEvents = arrayEvents

	resp = json.dumps(allEvents)
	if 'callback' in request.REQUEST:
		resp = callback + '(' + resp + ')'

	return HttpResponse(resp, content_type='application/json')

@ajax_view
def calendarmore(request, year, month, day):

	try:
		tasks_list = Task.objects.filter(users=request.user).filter(deadline=year+"-"+month+"-"+day).order_by('name').order_by('deadline')[1:]
	except Task.DoesNotExist:
		return HttpResponseRedirect("/")

	return render_to_response('MainApp/box_events.html', {'tasks_list': tasks_list})

login/views.py
from django.http import Http404
from django.shortcuts import render_to_response, get_object_or_404,render
from django.http import HttpResponse
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from django.core.context_processors import csrf


# from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.forms import AuthenticationForm
from login_forms import *
    
def login(request):
    # If we submitted the form...
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            # Correct password, and the user is marked "active"
            auth.login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect("/")#goes to the main page
        else:
            # Show an error page
            form = AuthenticationForm(request.POST)
            return render(request,'login.html',{'form':form}) 

    # If we didn't post, send the test cookie along with the login form.
    form = AuthenticationForm()
    return render(request,'login.html',{'form':form}) 

def new_user(request):
    return HttpResponseRedirect('/')
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/") 

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()#returns user
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            new_user = auth.authenticate(username=username, password=password)
            auth.login(request, new_user)
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
    
    #print response
    return render(request, "register.html", {
        'form': form,
    })
  

MainApp/templates/MainApp/box_events.html
<div class="box_event_outer">
	<div class="box_event_inner">
		{% for task in tasks_list %}
			{% if task.priority and task.priority == 1 %}
				<div class="event_line" style="background-color: red;">
			{% elif task.priority and task.priority == 2 %}
				<div class="event_line" style="background-color: yellow;">
			{% elif task.priority and task.priority == 3 %}
				<div class="event_line" style="background-color: green;">
			{% endif %}
					<a href="/tasks/{{task.pk}}/" class="ajax link_box">
						<h5 >{{task.name}}</h5>
					</a>
				</div>
		{% endfor %}
	</div>
</div>

MainApp/templates/MainApp/comment.html
<div class="inner-div content">
	
	<h2> Comment </h2>
	<p><em>User</em><br>{{comment.user}}</p>
	<p><em>Comment</em><br>{{comment.comment}}</p>
	<p><em>created</em><br>{{comment.created}}</p>
	<p><em>edited</em><br>{{comment.edited}}</p>
	<p><em>task</em><br><a href="{{ comment.task.get_absolute_url }}" class="ajax">{{comment.task}}</a></p>
	<p><em>group</em><br><a href="{{ comment.group.get_absolute_url }}" class="ajax">{{comment.group}}</a></p>

</div>

MainApp/templates/MainApp/group.html
<div class="inner-div content">
	
	<h2> Group: {{group.name }} </h2>
	<div class="section">
		<p class="description">{{group.description}}</p>
		<small>Participants:
			{% for user in group.users.all %}
				<a href="{{ user.get_absolute_url }}" class="ajax">{{user.username}}</a>&nbsp;
			{% endfor %}
		</small>
	<button class="btn btn-danger" data-toggle="modal" data-target="#gmodal">Delete group</button>
	</div>
	<div class="modal fade" id="gmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">Delete group</h4>
				</div>
				<div class="modal-body">
					Are you sure you want to delete {{group.name}}?
				</div>
				<div class="modal-footer">
					<button id="del_group" data-dismiss="modal" data-id="{{group.id}}" class="btn btn-default">Delete</button>

				</div>
			</div>
		</div>
	</div>
	<h3><small>Tasks</small></h3>
	<div class="section">
	{% for task in task_list %}
		<div class="cold-md-12 event">
			<a href="{{ task.get_absolute_url }}" class="ajax h4">{{task.name}}</a>

			<span>
			Deadline: {{task.deadline}} 
			{% if task.priority %}, Priority: {{task.priority}}{% endif %}
			{% if task.workload %}, Workload: {{task.workload}}{% endif %}  
			</span>
			<p class="fadez">{{task.description}}</p>
			<a href="{{ task.get_absolute_url }}" class="ajax read-more">Read more</a>
		</div>
	{% endfor %}
	<a href="/tasks_new/" class="ajax btn btn-default">Create a new task</a>
	</div>

	<h3><small>Comments</small></h3>
	<div class="section">
		<form id="form-comment" role="form" variety="groups" nro="{{group.pk}}" action="" method="post">
			{% csrf_token %}
			<div class="form-field">
				{{form.comment.errors}}
					
				{{form.comment}}
			</div>
			<input type="submit" value="Add Comment" />
		    <input type="hidden" name="next" value="{{ next|escape }}" />
		</form>

		{% for comment in comment_list %}
			<div class="cold-md-12 event">
				{% if comment.user == user %}
				<button type="button" class="close" data-toggle="modal" data-target="#cmodal{{comment.id}}">&times;</button>
		
				{% endif %}
				<p class="comment">{{ comment.comment }}</p>
				{# <a href="{{ comment.get_absolute_url }}" class="ajax">{{ comment.comment }}</a> #}
				<span>
				Posted by: {{comment.user.username}}, {{comment.created}} 
				{% if comment.edited < comment.created %}, edited: {{comment.edited}} {% endif %}
				</span>
			</div>
			{% if comment.user == user %}
			<div class="modal fade" id="cmodal{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-sm">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h4 class="modal-title" id="myModalLabel">Delete comment</h4>
						</div>
						<div class="modal-body">
							Are you sure you want to delete this comment?
						</div>
						<div class="modal-footer">
							<button id = "del_comment" data-id="{{comment.id}}" data-dismiss="modal" class="btn btn-default" >Delete</button>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	{# NEED TO LIST THE TASKS RELATED #}
</div>

MainApp/templates/MainApp/groups.html
	<div class="inner-div content">
	<a href="/groups_new/" class="ajax btn btn-default">Create a new group</a>
	<div class="row">
	{% for group in group_list %}
		<div class="cold-md-12 event">
			<a href="{{ group.get_absolute_url }}" class="ajax h4">{{group.name}}</a>

			<p class="fadez">{{group.description}}</p>
			<a href="{{ group.get_absolute_url }}" class="ajax read-more">Read more</a>
			
		</div>
	{% endfor %}
	</div>
	

</div>

MainApp/templates/MainApp/groups_new.html
<div class="inner-div content">
	<h2 class="text-center">Create a group</h2>
	<form id="form-group" role="form" action="" method="post">
		
			{% csrf_token %}
			<div class="form-group">
				{{form.name.errors}}
				<label for="id_name">Name:</label>
				{{form.name}}
			</div>
			
			<div class="form-group">
				
				{{form.description.errors}}
				<label for="id_description">Description:</label>
				{{form.description}}

			</div>

			<div class="form-group">
				{{form.users.errors}}
				<label for="id_users">Users:</label>
				{{form.users}}
			</div>
		    <input class="button btn-default btn-block" type="submit" value="Create" />
		    <input type="hidden" name="next" value="{{ next|escape }}" />
		
 	</form>

</div>

MainApp/templates/MainApp/home.html
{% extends 'base.html' %}

{% block pagetitle %}Home{% endblock %}

{% block navbar %}
	{% include "navbar.html" %}
{% endblock %}

{% block left-panel %}		
	<div class="inner-div content">
		{% for event in latest %}
			<div class="cold-md-10 event">
				{% if event.type == "group"%}
					New group <a href='{{event.get_absolute_url}}' class='ajax'><b>{{event.name}}</b></a> was created.
				{% elif event.type == "task"%}
					New task <a href='{{event.get_absolute_url}}' class='ajax'><b>{{event.name}}</b> </a>
					{%if event.group %}
						for group <a href='{{event.group.get_absolute_url}}' class='ajax'><b>{{event.group.name}}</b> </a>
					{%endif%}
					 was created.
				{% elif event.type == "comment"%}
					{% if event.task %}
						New comment in task <a href='{{event.task.get_absolute_url}}' class='ajax'><b>{{event.task.name}}</b></a>
					{% elif event.group %}
						New comment in group <a href ='{{event.group.get_absolute_url}}' class='ajax'><b>{{event.group.name}}</b></a>
					{% endif %}
				{% endif %}
			</div>
		{% empty %}
			No new events were found.
		{% endfor %}

	</div>
{% endblock %}

MainApp/templates/MainApp/login.html
{% extends 'base.html' %}

{% block head %}
	<style>
		.navbar-default .navbar-nav>li>a {color: white;}
		.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:hover, .navbar-default .navbar-nav>.active>a:focus {background-color: transparent;}
	</style>
{% endblock %}

{% block container %}
<div class="container-fluid text-center" style="background-color: #eee;">
	<h4>TASK MANAGER 2014</h4>
</div>

<div class="container-fluid jumbotron homePage">
	<div class="row">
		<div class="col-md-4 col-md-offset-5 centered" class="divForm">
			<form role="form" class="form-horizontal">
				<div class="form-group">
					<label for="username" class="col-md-3 control-label">Username</label>
					<div class="col-md-6">
						<input type="text" class="form-control" id="username" placeholder="Username" name="username">
					</div>
				</div>
				<div class="form-group">
					<label for="password" class="col-md-3 control-label">Password</label>
					<div class="col-md-6">
						<input type="password" class="form-control" id="password" placeholder="Password" name="password">
					</div>
				</div>
				<div class="form-ggroup">
					<div class="col-md-4 small">
						<small>Not register?<br> <a href="#regiter">Register now!</a></small>
					</div>
					<button type="submit" class="btn btn-primary btn-sm">Login</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

MainApp/templates/MainApp/profile.html
<div class="inner-div content">
	
	User profile for <b>{{user.first_name}} {{user.last_name}}</b><br>
	This is for your own profile, settings etcetc should be here.
</div>


MainApp/templates/MainApp/small_task_list.html
<div class="inner-div content">
	<div class="row">
	{% for task in task_list %}
		<div class="cold-md-12 event prio{{task.priority}}">
			

			<a href="{{ task.get_absolute_url }}" class="ajax read-more" style="color:black;">{{task.name}}</a>
			<small style="float:right;">{{task.deadline}}</small>
		</div>
	{% endfor %}
	</div>
	
	

</div>

MainApp/templates/MainApp/tasks.html
<div class="inner-div content">
	<a href="/tasks_new/" class="ajax btn btn-default">Create a new task</a>
	<div class="row">
	{% for task in task_list %}
		<div class="cold-md-12 event">
			<a href="{{ task.get_absolute_url }}" class="ajax h4">{{task.name}}</a>
			<span>
			Deadline: {{task.deadline}} 
			{% if task.priority %}, Priority: {{task.priority}}{% endif %}
			{% if task.workload %}, Workload: {{task.workload}}{% endif %}  
			</span>
			<p class="fadez">{{task.description}}</p>
			<a href="{{ task.get_absolute_url }}" class="ajax read-more">Read more</a>
			
		</div>
	{% endfor %}
	</div>
	
	

</div>


MainApp/templates/MainApp/tasks_new.html

	<div class="inner-div content">
	<h2 class="text-center">Create a task</h2>
	<form id="form-task" role="form" action="" method="post">
			
			{% csrf_token %}
			<div class="form-group">
				{{form.name.errors}}
				<label for="id_name">Name:</label>
				{{form.name}}
			</div>
			<div class="form-group">
				{{form.description.errors}}
				<label for="id_description">Description:</label>
				{{form.description}}
			</div>
			<div class="form-group">
				{{form.group.errors}}
				<label for="id_group">group:</label>
				{{form.group}}
			</div>
			<div class="form-group">
				{{form.users.errors}}
				<label for="id_users">Users:</label>
				{{form.users}}
			</div>
			<div class="form-group">
				{{form.deadline.errors}}
				<label for="id_deadline">Deadline:</label>
				{{form.deadline}}
				<span class="help-block">'2006-10-25' or '10/25/2006' or '10/25/06'</span>
			</div>
			<div class="form-group">
				{{form.priority.errors}}
				<label for="id_priority">priority:</label>
				{{form.priority}}
			</div>

			<div class="form-group">
				{{form.workload.errors}}
				<label for="id_workload">workload:</label>
				{{form.workload}}
			</div>

		    <input class="button btn-default btn-block" type="submit" value="Create" />
		    <input type="hidden" name="next" value="{{ next|escape }}" />
		
 	</form>
</div>

MainApp/templates/MainApp/user.html
<div class="inner-div content">
	
	<h2> User </h2>
	<p><em>Username</em><br>{{user.username}}</p>
	
	<h2>{{user.username}}'s Groups</h2>	
	<ul>
	{% for group in group_list %}
		<li><a href="{{ group.get_absolute_url }}" class="ajax">{{ group.name }}</a></li>
	{% endfor %}
	</ul>

</div>